# Generated by Django 4.2.7 on 2024-01-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
