# Generated by Django 4.2.7 on 2024-01-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
